START TRANSACTION;
DROP DATABASE IF EXISTS Gestion_Escuela;
CREATE DATABASE Gestion_Escuela DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish_ci;
USE Gestion_Escuela;

CREATE TABLE Aplicaciones
(
	idAplicacion TINYINT UNSIGNED AUTO_INCREMENT,
	nombre VARCHAR(60) NOT NULL UNIQUE,
	descripcion VARCHAR(200) NOT NULL,
	url VARCHAR(200) NOT NULL,
	icono VARCHAR(200) NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP,
	
	PRIMARY KEY(idAplicacion)
)ENGINE=INNODB;

CREATE TABLE Perfiles
(
	idPerfil TINYINT UNSIGNED AUTO_INCREMENT,
	nombre VARCHAR(60) NOT NULL UNIQUE,
	descripcion VARCHAR(200) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP,
	
	PRIMARY KEY(idPerfil)
)ENGINE=INNODB;

CREATE TABLE Aplicaciones_Perfiles
(
	idPerfil TINYINT UNSIGNED,
	idAplicacion TINYINT UNSIGNED,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP,
	
	CONSTRAINT PK_Aplicaciones_Perfiles PRIMARY KEY (idPerfil, idAplicacion),
	
	CONSTRAINT FK_Aplicaciones_Perfiles_Perfiles 
		FOREIGN KEY (idPerfil) 
			REFERENCES Perfiles (idPerfil) 
				ON DELETE CASCADE 
				ON UPDATE CASCADE,
				
	CONSTRAINT FK_Aplicaciones_Perfiles_Aplicaciones 
		FOREIGN KEY (idAplicacion) 
			REFERENCES Aplicaciones (idAplicacion) 
				ON DELETE CASCADE 
				ON UPDATE CASCADE
)ENGINE=INNODB;

CREATE TABLE Usuarios
(
	idUsuario SMALLINT UNSIGNED AUTO_INCREMENT,
	nombre VARCHAR(60) NOT NULL,
	correo VARCHAR(60) NOT NULL UNIQUE,
	bajaTemporal BIT NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP,
	
	PRIMARY KEY(idUsuario)
)ENGINE=INNODB;

CREATE TABLE Perfiles_Usuarios
(
	idPerfil TINYINT UNSIGNED,
	idUsuario SMALLINT UNSIGNED,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP,
	
	CONSTRAINT PK_Perfiles_Usuarios PRIMARY KEY (idPerfil, idUsuario),
	
	CONSTRAINT FK_Perfiles_Usuarios_Perfiles 
		FOREIGN KEY (idPerfil) 
			REFERENCES Perfiles (idPerfil) 
				ON DELETE CASCADE 
				ON UPDATE CASCADE,
				
	CONSTRAINT FK_Perfiles_Usuarios_Usuarios 
		FOREIGN KEY (idUsuario) 
			REFERENCES Usuarios (idUsuario) 
				ON DELETE CASCADE 
				ON UPDATE CASCADE
)ENGINE=INNODB;

CREATE TABLE Etapas
(
	idEtapa TINYINT UNSIGNED AUTO_INCREMENT,
	codEtapa CHAR(5) NOT NULL UNIQUE,
	nombre VARCHAR(40) NOT NULL UNIQUE,
	idCoordinador SMALLINT UNSIGNED NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP,
	
	PRIMARY KEY(idEtapa),
	
	CONSTRAINT FK_Etapas_Usuarios 
		FOREIGN KEY (idCoordinador) 
			REFERENCES Usuarios (idUsuario) 
				ON DELETE SET NULL 
				ON UPDATE CASCADE
)ENGINE=INNODB;

CREATE TABLE Subetapas
(
	idEtapa TINYINT UNSIGNED,
	idEtapaPadre TINYINT UNSIGNED,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP,
	
	CONSTRAINT PK_Subetapas PRIMARY KEY (idEtapa, idEtapaPadre),
	
	CONSTRAINT FK_Subetapas_Etapas
		FOREIGN KEY (idEtapa) 
			REFERENCES Etapas (idEtapa) 
				ON DELETE CASCADE 
				ON UPDATE CASCADE,
				
	CONSTRAINT FK_Subetapas_EtapasPadre
		FOREIGN KEY (idEtapaPadre) 
			REFERENCES Etapas (idEtapa) 
				ON DELETE CASCADE
				ON UPDATE CASCADE
)ENGINE=INNODB;

CREATE TABLE Cursos
(
	idCurso TINYINT UNSIGNED AUTO_INCREMENT,
	codCurso CHAR(5) NOT NULL UNIQUE,
	nombre VARCHAR(40) NULL UNIQUE,
	idEtapa TINYINT UNSIGNED NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP,
	
	PRIMARY KEY(idCurso),
	
	CONSTRAINT FK_Cursos_Etapas
		FOREIGN KEY (idEtapa) 
			REFERENCES Etapas (idEtapa) 
				ON DELETE CASCADE 
				ON UPDATE CASCADE
)ENGINE=INNODB;

CREATE TABLE FP_Departamentos
(
	idDepartamento TINYINT UNSIGNED AUTO_INCREMENT,
	nombre VARCHAR(40) NOT NULL UNIQUE,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP,
	
	PRIMARY KEY(idDepartamento)
)ENGINE=INNODB;

CREATE TABLE FP_FamiliasProfesionales
(
	idFamilia TINYINT UNSIGNED AUTO_INCREMENT,
	nombre VARCHAR(40) NOT NULL UNIQUE,
	idDepartamento TINYINT UNSIGNED NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP,
	
	PRIMARY KEY(idFamilia),
	
	CONSTRAINT FK_FP_FamiliasProfesionales_FP_Departamentos
		FOREIGN KEY (idDepartamento) 
			REFERENCES FP_Departamentos (idDepartamento) 
				ON DELETE SET NULL
				ON UPDATE CASCADE
)ENGINE=INNODB;

CREATE TABLE FP_Ciclos
(
	idCiclo TINYINT UNSIGNED AUTO_INCREMENT,
	codCiclo CHAR(4) NOT NULL UNIQUE,
	nombre VARCHAR(40) NOT NULL UNIQUE,
	idFamilia TINYINT UNSIGNED NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP,
	
	PRIMARY KEY(idCiclo),
	
	CONSTRAINT FK_FP_Ciclos_FP_FamiliasProfesionales
		FOREIGN KEY (idFamilia)
			REFERENCES FP_FamiliasProfesionales (idFamilia) 
				ON DELETE SET NULL 
				ON UPDATE CASCADE
)ENGINE=INNODB;

CREATE TABLE FP_Ciclos_Cursos
(
	idCiclo TINYINT UNSIGNED,
	idCurso TINYINT UNSIGNED, 
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP,
	
	CONSTRAINT PK_FP_Ciclos_Cursos PRIMARY KEY (idCiclo, idCurso),
	
	CONSTRAINT FK_FP_Ciclos_Cursos_FP_Ciclos
		FOREIGN KEY (idCiclo)
			REFERENCES FP_Ciclos (idCiclo) 
				ON DELETE CASCADE 
				ON UPDATE CASCADE,
				
	CONSTRAINT FK_FP_Ciclos_Cursos_Cursos
		FOREIGN KEY (idCurso)
			REFERENCES Cursos (idCurso) 
				ON DELETE CASCADE 
				ON UPDATE CASCADE
)ENGINE=INNODB;

CREATE TABLE Secciones
(
	idSeccion SMALLINT UNSIGNED AUTO_INCREMENT,
	codSeccion CHAR(6) NOT NULL UNIQUE,
	nombre VARCHAR(100) NOT NULL UNIQUE,
	idTutor SMALLINT UNSIGNED NULL UNIQUE,
	idCurso TINYINT UNSIGNED NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP,
	
	PRIMARY KEY(idSeccion),
	
	CONSTRAINT FK_Secciones_Usuarios
		FOREIGN KEY (idTutor)
			REFERENCES Usuarios (idUsuario) 
				ON DELETE SET NULL 
				ON UPDATE CASCADE,
				
	CONSTRAINT FK_Secciones_Cursos
		FOREIGN KEY (idCurso)
			REFERENCES Cursos (idCurso) 
				ON DELETE CASCADE 
				ON UPDATE CASCADE
)ENGINE=INNODB;

CREATE TABLE Alumnos
(
	idAlumno INT UNSIGNED AUTO_INCREMENT,
	NIA INT UNSIGNED NOT NULL UNIQUE,
	nombre VARCHAR(60) NOT NULL,
	DNI CHAR(9) NOT NULL,
	idSeccion SMALLINT UNSIGNED NOT NULL,
	correo VARCHAR(60) NULL,
	sexo ENUM('m','f') NOT NULL,
	telefono CHAR(9) NOT NULL,
	telefonoUrgencia CHAR(9) NULL,
	fechaNacimiento DATE NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP,
	
	PRIMARY KEY(idAlumno),
	
	CONSTRAINT FK_Alumnos_Secciones
		FOREIGN KEY (idSeccion)
			REFERENCES Secciones (idSeccion) 
				ON DELETE CASCADE 
				ON UPDATE CASCADE
)ENGINE=INNODB;

INSERT INTO
	Perfiles (nombre, descripcion)
VALUES 
	('Administrador', 'Administrador'),
	('Gestor', 'Gestor'),
	('Profesor', 'Profesor'),
	('Tutor', 'Tutor');
COMMIT;